// Created by szatpig at 2019/8/19.



const LOGIN_REQUEST = 'LOGIN_REQUEST';
const USER_LOGIN = 'USER_LOGIN';
const USER_TOKEN = 'USER_TOKEN';
const USER_INFO = 'USER_INFO';
const USER_MENU_LIST = 'USER_MENU_LIST';
const USER_LOGIN_OUT = 'USER_LOGIN_OUT';

const HEADER_COLLAPSED = 'HEADER_COLLAPSED';

const SYSTEM_USER_LIST = 'SYSTEM_USER_LIST';
const SYSTEM_USER_LIST_REQUEST = 'SYSTEM_USER_LIST_REQUEST'
const TABLE_DATA = 'TABLE_DATA'

const FETCH_ERROR = 'FETCH_ERROR';

export {
    USER_TOKEN,
    FETCH_ERROR,
    //request 请求
    LOGIN_REQUEST,
    USER_LOGIN,
    USER_MENU_LIST,
    USER_INFO,
    USER_LOGIN_OUT,
    //header
    HEADER_COLLAPSED,
    //system
    SYSTEM_USER_LIST,
    SYSTEM_USER_LIST_REQUEST,
    TABLE_DATA
}
